// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"perfect-pic-server/internal/config"
	"perfect-pic-server/internal/handler"
	"perfect-pic-server/internal/pkg/cache"
	"perfect-pic-server/internal/pkg/database"
	"perfect-pic-server/internal/pkg/email"
	"perfect-pic-server/internal/pkg/jwt"
	"perfect-pic-server/internal/pkg/redis"
	"perfect-pic-server/internal/repository"
	"perfect-pic-server/internal/router"
	"perfect-pic-server/internal/service"
	"perfect-pic-server/internal/usecase/admin"
	"perfect-pic-server/internal/usecase/app"
)

// Injectors from wire.go:

func InitializeApplication() (*Application, error) {
	configConfig := config.NewStaticConfig()
	dbConnectionConfig := config.NewDBConnectionConfig(configConfig)
	db, err := database.NewGormDB(dbConnectionConfig)
	if err != nil {
		return nil, err
	}
	settingStore := repository.NewSettingRepository(db)
	dbConfig := config.NewDBConfig(settingStore)
	authService := service.NewAuthService(dbConfig, configConfig)
	captchaService := service.NewCaptchaService(dbConfig)
	userStore := repository.NewUserRepository(db)
	redisConfig := config.NewRedisClientConfig(configConfig)
	client := redis.NewRedisClient(redisConfig)
	cacheConfig := config.NewCacheConfig(configConfig)
	store := cache.NewStore(client, cacheConfig)
	jwtConfig := config.NewJWTConfig(configConfig)
	jwtJWT := jwt.NewJWT(jwtConfig)
	userService := service.NewUserService(userStore, dbConfig, store, jwtJWT)
	mailer := email.NewMailer()
	emailService := service.NewEmailService(dbConfig, mailer)
	systemStore := repository.NewSystemRepository(db)
	initService := service.NewInitService(systemStore, dbConfig)
	authUseCase := app.NewAuthUseCase(authService, userStore, userService, emailService, initService, dbConfig)
	passkeyStore := repository.NewPasskeyRepository(db)
	passkeyService := service.NewPasskeyService(passkeyStore, dbConfig, store)
	passkeyUseCase := app.NewPasskeyUseCase(passkeyService, passkeyStore, authService, userStore)
	authHandler := handler.NewAuthHandler(authService, captchaService, authUseCase, initService, dbConfig, passkeyUseCase)
	imageStore := repository.NewImageRepository(db)
	statUseCase := admin.NewStatUseCase(imageStore, userStore)
	systemHandler := handler.NewSystemHandler(initService, statUseCase, dbConfig, userService)
	settingsService := service.NewSettingsService(settingStore, dbConfig)
	settingsUseCase := admin.NewSettingsUseCase(emailService)
	settingsHandler := handler.NewSettingsHandler(settingsService, settingsUseCase)
	userUseCase := app.NewUserUseCase(userService, userStore, emailService, dbConfig)
	imageService := service.NewImageService(imageStore, dbConfig, configConfig)
	userManageUseCase := admin.NewUserManageUseCase(userService, imageService, passkeyService)
	imageUseCase := app.NewImageUseCase(imageService, userService, userStore, configConfig, dbConfig)
	userHandler := handler.NewUserHandler(userService, userUseCase, userManageUseCase, imageService, imageUseCase, authService, passkeyService, passkeyUseCase, client)
	imageHandler := handler.NewImageHandler(imageService, imageUseCase)
	routerRouter := router.NewRouter(authHandler, systemHandler, settingsHandler, userHandler, imageHandler, dbConfig, db, client)
	application := NewApplication(routerRouter, dbConfig, db, client)
	return application, nil
}
